git:
        submodules: false

notifications:
        emails: false

before_install:
        - git submodule update --init ./external/libzmq
        - git submodule update --init ./external/czmq
        - git submodule update --init ./external/jsmn
        - git submodule update --init ./external/klib
        - git submodule update --init ./external/cmocka
        - git clone https://github.com/nodejs/http-parser ./external/http_parser

matrix:
        include:
                - os: linux
                  name: Linux/C/CMake/Debug
                  language: c
                  script:
                          - cmake -DCMAKE_INSTALL_PREFIX=./build/install . 
                          - cmake --build ./ --target install
                - os: linux
                  name: Linux/C/CMake/Test
                  dist: bionic
                  language: c
                  addons:
                          apt:
                                  packages:
                                  - lcov
                                  - valgrind
                  script:
                          - cmake -DCMAKE_INSTALL_PREFIX=./build/install -DENABLE_TESTING=ON . 
                          - cmake --build ./ --target install
                          - ctest -T memcheck
                          - make test-coverage
                  after_success:
                          - bash <(curl -s https://codecov.io/bash) -f test-coverage.info.cleaned
                - os: linux
                  name: Linux/Rust/Cargo/Debug
                  language: rust
                  rust:
                          - nightly
                  script:
                          - cargo build --verbose --all
                - os: windows
                  name: Windows/C/VS/Debug
                  language: c
                  script: 
                          - cmake -DCMAKE_INSTALL_PREFIX:PATH=./build/install .
                          - cmake --build ./ --target install
                - os: windows
                  name: Windows/Rust/Cargo/Debug
                  language: rust
                  rust:
                          - nightly
                  script:
                          - cargo build --verbose --all
