git:
        submodules: false
notifications:
        emails: false
matrix:
        include:
                - os: linux
                  dist: bionic
                  language: c
                  addons:
                          apt:
                                  packages:
                                          - lcov
                                          - valgrind
                  env: 
                        - WITH_SQLITE=ON
                          ENABLE_TESTING=ON
                          BUILD_EXAMPLES=ON
                  script:
                          - ./scripts/ci/build-c.sh
