git:
        submodules: false
notifications:
        emails: false
matrix:
        include:
                - os: linux
                  dist: bionic
                  language: c
                  addons:
                          apt:
                                  packages:
                                          - lcov
                                          - valgrind
                  env: 
                          - WITH_SQLITE=ON
                            ENABLE_TESTING=ON
                            BUILD_EXAMPLES=ON
                  script:
                          - ./scripts/ci/build-c.sh
                - os: linux
                  dist: bionic
                  language: c
                  env:
                          - BUILD_EXAMPLES=ON
                  script:
                          - ./scripts/ci/build-c.sh
                - os: linux
                  dist: bionic
                  language: c
                  addons:
                          apt:
                                  packages:
                                          - libzmq3-dev
                                          - libczmq-dev
                  env:
                          - WITH_SQLITE=ON
                            BUILD_EXAMPLES=ON
                            USE_SYSTEM_ZMQ=ON
                            USE_SYSTEM_OPENSSL=ON
                  script:
                          - ./scripts/ci/build-c.sh
                - os: linux
                  dist: bionic
                  language: node_js
                  node_js:
                          - 10
                  env:
                          - USE_SYSTEM_OPENSSL=ON
                  script:
                          - ./scripts/ci/build-nodejs.sh
                - os: linux
                  dist: bionic
                  language: rust
                  rust:
                          - nightly
                  env:
                          - USE_SYSTEM_OPENSSL=ON
                  script:
                          - ./scripts/ci/build-rust.sh
