os: linux
dist: bionic
env:
        - WITH_SQLITE=ON ENABLE_TESTING=ON
        - WITH_SQLITE=OFF
matrix:
        include:
                - language: c
                  script:
                          - cmake -DCMAKE_INSTALL_PREFIX=./install
                            -DWITH_SQLITE=$WITH_SQLITE
                            -DENABLE_TESTING=$ENABLE_TESTING .
                          - cmake --build . --target install
                          - if [ $ENABLE_TESTING ]; then
                            ctest -T memcheck &&
                            make test-coverage &&
                            bash <(curl -s https://codecov.io/bash) 
                                 -f test-coverage.info;
                            fi

