git:
        submodules: false

before_install:
        - git submodule update --init ./external/libzmq
        - git submodule update --init ./external/czmq
        - git submodule update --init ./external/jsmn
        - git submodule update --init ./external/klib
        - git submodule update --init ./external/cmocka
        - git submodule update --init ./external/http_parser

matrix:
        include:
                - os: linux
                  language: c
                  script:
                          - cmake -DCMAKE_INSTALL_PREFIX=./build/install . 
                          - cmake --build ./ --target install
                - os: linux
                  dist: bionic
                  language: c
                  addons:
                          apt:
                                  packages:
                                  - lcov
                                  - valgrind
                  script:
                          - cmake -DCMAKE_INSTALL_PREFIX=./build/install -DENABLE_TESTING=ON . 
                          - cmake --build ./ --target install
                          - ctest -T memcheck
                - os: linux
                  language: rust
                  rust:
                          - nightly
                  script:
                          - cargo build --verbose --all
                - os: windows
                  language: c
                  script: 
                          - cmake -DCMAKE_INSTALL_PREFIX:PATH=./build/install .
                          - cmake --build ./ --target install
                - os: windows
                  language: rust
                  rust:
                          - nightly
                  script:
                          - cargo build --verbose --all
