git:
        submodules: false

before_install:
        - git submodule update --init ./external/libzmq
        - git submodule update --init ./external/czmq
        - git submodule update --init ./external/jsmn
        - git submodule update --init ./external/klib

matrix:
        include:
                - os: linux
                  language: c
                  script:
                        cmake -DCMAKE_INSTALL_PREFIX=./build/install . && cmake --build ./ --target install
                - os: linux
                  language: rust
                  script:
			curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -y && \
			rustup default nightly && \
			rustup update && \
			cargo build
                - os: windows
                  language: c
                  script:
                        cmake -DCMAKE_INSTALL_PREFIX:PATH=./build/install . && cmake --build ./ --target install
