git:
        submodules: false
notifications:
        emails: false
matrix:
        include:
                - os: linux
                  dist: bionic
                  language: c
                  addons:
                          apt:
                                  packages:
                                          - lcov
                                          - valgrind
                  env: 
                          - BUILD_LINQD=ON
                            USE_SYSTEM_OPENSSL=ON
                            ENABLE_TESTING=ON
                  script:
                          - ./scripts/ci/build-c.sh
                - os: linux
                  dist: bionic
                  language: c
                  env:
                  script:
                          - ./scripts/ci/build-c.sh
                - os: linux
                  dist: bionic
                  language: c
                  addons:
                          apt:
                                  packages:
                                          - libzmq3-dev
                                          - libczmq-dev
                  env:
                          - BUILD_LINQD=ON
                            USE_SYSTEM_OPENSSL=ON
                            USE_SYSTEM_ZMQ=ON
                  script:
                          - ./scripts/ci/build-c.sh
                - os: linux
                  dist: bionic
                  language: node_js
                  node_js:
                          - 10
                  env:
                          - LINQ_NETWORK_WITH_DAEMON=ON
                          - USE_SYSTEM_OPENSSL=ON
                  script:
                          - ./scripts/ci/build-nodejs.sh
                - os: linux
                  dist: bionic
                  language: node_js
                  node_js:
                          - 10
                  env:
                  script:
                          - ./scripts/ci/build-nodejs.sh
                - os: linux
                  dist: bionic
                  language: rust
                  rust:
                          - nightly
                  env:
                  script:
                          - ./scripts/ci/build-rust.sh
                - os: windows
                  language: c
                  env:
                  script:
                          - ./scripts/ci/build-c.sh
                - os: windows
                  language: node_js
                  node_js:
                          - 10
                  env:
                  script:
                          # https://github.com/appveyor/ci/issues/2420
                          - export PATH="$PATH:/c/Program Files/Git/mingw64/libexec/git-core"
                          - ./scripts/ci/build-nodejs.sh
                - os: windows
                  env: GENERATOR="Visual Studio 15 2017"
                  language: rust
                  rust:
                          - nightly
                  script:
                          - ./scripts/ci/build-rust.sh
