# Note 'bionic' libc is too old to link with our nodejs prebuilt binaries. So
# for prebuilt binary test we use the focal vm.
# An alternative would be to build the prebuilt binaries with:
# https://github.com/wheybags/glibc_version_header
git:
        submodules: false
notifications:
        emails: false

before_install:
        # https://github.com/appveyor/ci/issues/2420 (git-sh-setup: not found)
        # - export PATH="$PATH:/c/Program Files/Git/mingw64/libexec/git-core"
        # (Work around, manually loading submodules)
        - git submodule update --init ./external/libzmq
        - git submodule update --init ./external/czmq
        - git submodule update --init ./external/jsmn-web-tokens
        - git submodule update --init ./external/libusb

matrix:
        include:
                - os: linux
                  dist: bionic
                  language: c
                  addons:
                          apt:
                                  packages:
                                          - lcov
                                          - valgrind
                                          - libudev-dev
                  env: 
                          - BUILD_LINQD=ON
                            BUILD_USBD=ON
                            BUILD_USBH=ON
                            BUILD_DEPENDENCIES=ON
                            ENABLE_TESTING=ON
                  script:
                          - ./scripts/ci/build-c.sh
                - os: linux
                  dist: bionic
                  language: c
                  env:
                          - BUILD_DEPENDENCIES=ON
                  script:
                          - ./scripts/ci/build-c.sh
                - os: linux
                  dist: bionic
                  language: c
                  addons:
                          apt:
                                  packages:
                                          - libzmq3-dev
                                          - libczmq-dev
                  env:
                          - BUILD_LINQD=ON
                  script:
                          - ./scripts/ci/build-c.sh
                - os: linux
                  dist: bionic
                  language: node_js
                  node_js:
                          - 12
                  env:
                          - LINQ_NETWORK_WITH_LINQD=ON
                  script:
                          - ./scripts/ci/build-nodejs.sh
                - os: linux
                  env:
                  dist: bionic
                  language: node_js
                  node_js:
                          - 12
                  script:
                          - ./scripts/ci/build-nodejs.sh
                - os: linux
                  env:
                          - LINQ_NETWORK_USE_PREBUILT=ON
                  dist: focal
                  language: node_js
                  node_js:
                          - 12
                - os: linux
                  dist: bionic
                  language: rust
                  rust:
                          - nightly
                  env:
                  script:
                          - ./scripts/ci/build-rust.sh
                - os: windows
                  language: c
                  env:
                          - BUILD_DEPENDENCIES=ON
                  script:
                          - ./scripts/ci/build-c.sh
                - os: windows
                  language: c
                  env:
                          - BUILD_LINQD=ON
                            BUILD_USBH=ON
                            BUILD_DEPENDENCIES=ON
                            GENERATOR="Visual Studio 15 2017 Win64"
                  script:
                          - choco install openssl
                          - ./scripts/ci/build-c.sh
                - os: windows
                  language: node_js
                  node_js:
                          - 12
                  env:
                  script:
                          - ./scripts/ci/build-nodejs.sh
                - os: windows
                  language: node_js
                  node_js:
                          - 12
                  env:
                          - LINQ_NETWORK_USE_PREBUILT=ON
                  script:
                          - ./scripts/ci/build-nodejs.sh
                - os: windows
                  env: GENERATOR="Visual Studio 15 2017"
                  language: rust
                  rust:
                          - stable
                  script:
                          - ./scripts/ci/build-rust.sh
