[package]
name = "linq-io"
version = "0.1.0"
authors = ["thomas <thomas.chiantia@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linq-io-sys = { path = "../linq-io-sys" }
futures = "0.3.1"
