version: 2.1

orbs:
        win: circleci/windows@2.2.0

jobs:
        build-windows:
                executor: win/default
                steps:
                        - add_ssh_keys:
                                fingerprints:
                                        - "07:a2:81:7c:93:cb:8b:03:f4:d9:31:6d:29:6b:ea:07"
                        - checkout
                        - run: Write-Host "Hello"

workflows:
        version: 2.1
        build_and_test:
                jobs:
                        - build-windows
