version: 2.1

orbs:
        win: circleci/windows@2.2.0

jobs:
        build-windows:
                executor: win/default
                steps:
                        - checkout
                        - run:
                                name: "Pull Dependency (zmq)"
                                command: "git submodule update --init ./external/libzmq"
                        - run:
                                name: "Pull Dependency (czmq)"
                                command: "git submodule update --init ./external/czmq"
                        - run:
                                name: "Pull Dependency (jsmn)"
                                command: "git submodule update --init ./external/jsmn"
                        - run:
                                name: "Pull Dependency (klib)"
                                command: "git submodule update --init ./external/klib"
                        - run:
                                name: "Install CMake"
                                command: "choco install cmake -y; setx /m PATH \"C:\\Program Files\\CMake\\bin;%PATH%\""
                        - run:
                                name: "Create Build Files"
                                command: "cmake -DCMAKE_INSTALL_PREFIX=./install -B./build ."
                        - run:
                                name: "Build"
                                command: "cmake --build ./build"

workflows:
        version: 2.1
        build_and_test:
                jobs:
                        - build-windows
