[package]
name = "events"
version = "0.1.0"
authors = ["thomas <thomas.chiantia@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atx-net = { path = "../../atx-net" }
futures = "0.3.1"
futures-timer = "2.0.2"
async-std = "1.1.0"
async-attributes = "1.1.1"
