[package]
name = "event_listener"
version = "0.1.0"
authors = ["thomas <thomas.chiantia@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linq-netw = { path = "../../linq-netw" }
futures = "0.3.1"
