[package]
name = "example"
version = "0.1.0"
authors = ["thomas <thomas.chiantia@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linq = { path = "../linq" }
ctrlc = "3.1.3"
rocket = "0.4.2"
